config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  scope path: 'admin', module: 'admin' do
    get '/' => 'dashboard#index', as: :dashboard
    get '/slacktown' => 'dashboard#slacktown', as: :slacktown
    get '/mailtown' => 'dashboard#mailtown', as: :mailtown
    get '/errortown' => 'dashboard#errortown', as: :errortown

    resources :conferences, param: :slug do
      member do
        get :attendees_keeper
        get :sponsors_yml
        get :sponsors_json
        get :asset_urls
        get :table_view
      end

      resource :booth_assignment, only: %i(show update)

      resources :form_descriptions, param: :locale, except: %i(index)
      resources :plans, except: %i(show)

      resources :sponsorships, except: %i(index new create) do
        resources :sponsorship_editing_histories, as: :editing_histories, path: 'editing_history', only: %i(index)
        resources :sponsorship_staff_notes, as: :staff_notes, path: 'staff_notes', only: %i(index create edit update destroy)
        resource :impersonation, only: %i(create), controller: 'sponsorship_impersonations'
        member do
          get :download_asset
        end
      end

      resources :sponsor_events, path: 'events', except: %i(new create destroy) do
        resources :sponsor_event_editing_histories, as: :editing_histories, path: 'editing_history', only: %i(index)
        member do
          get :download_asset
        end
      end

      resources :announcements
      resources :broadcasts do
        resources :broadcast_deliveries, as: :deliveries, path: 'deliveries', only: %i(create destroy)
        member do
          post :dispatch_delivery
        end
      end
    end

    resources :organizations, param: :slug, only: %i(index new create show edit update), constraints: {slug: /[^\/]+/}

    resource :session, only: %i(new destroy) do
      get :rise, as: :rise
    end
  end

  get '/auth/:provider/callback' => 'admin/sessions#create'

  get '/' => 'root#index'

  scope as: :user do
    resource :session, only: %i(new create destroy) do
      get 'claim/:handle', action: :claim, as: :claim
    end

    resources :conferences, param: :slug, only: %i(index) do
      resource :sponsorship, only: %i(new create show edit update) do
        resources :broadcasts, only: %i(index)
        resource :exhibition, only: %i(new create edit update)
        resources :events, controller: 'sponsor_events', only: %i(new create show edit update destroy)
        resources :pass_redemptions, only: %i(index) do
          member do
            resource :retraction, only: %i(new create show), controller: 'pass_retractions'
          end
        end
      end
      resources :sponsorship_asset_files, only: %i(create update show) do
        member do
          post :initiate_update
        end
      end
      resources :event_asset_files, controller: 'sponsor_event_asset_files', only: %i(create update show) do
        member do
          post :initiate_update
        end
      end
    end


    post '/webhooks/mailgun' => 'webhooks/mailgun#webhook'
  end


  get '/site/sha' => RevisionPlate::App.new(File.join(__dir__, '..', 'REVISION'))
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sponsor_event.rb
class SponsorEvent < ApplicationRecord
  include EditingHistoryTarget

  belongs_to :sponsorship
  belongs_to :conference
  has_one :asset_file, class_name: 'SponsorEventAssetFile', dependent: :destroy

  enum :status, { pending: 0, accepted: 1, rejected: 2, withdrawn: 3 }

  validates :slug, presence: true, uniqueness: { scope: :conference_id }
  validates :title, presence: true
  validates :starts_at, presence: true
  validates :url, presence: true, format: { with: %r{\Ahttps?://}, message: "must be a valid HTTP(S) URL" }
  validate :validate_co_host_sponsorship_ids
  validate :validate_policy_acknowledged_on_create, on: :create

  before_validation :set_conference_from_sponsorship
  before_validation :generate_slug, on: :create

  scope :by_starts_at, -> { order(starts_at: :asc) }

  def editable_by_sponsor?
    !withdrawn?
  end

  def to_h_for_history
    {
      "sponsorship_id" => sponsorship_id,
      "conference_id" => conference_id,
      "slug" => slug,
      "title" => title,
      "starts_at" => starts_at&.iso8601,
      "url" => url,
      "price" => price,
      "capacity" => capacity,
      "location_en" => location_en,
      "location_local" => location_local,
      "status" => status,
      "co_host_sponsorship_ids" => co_host_sponsorship_ids,
      "link_name" => link_name,
      "admin_comment" => admin_comment,
      "asset_file_id" => asset_file&.id,
      "asset_file_version_id" => asset_file&.version_id,
      "asset_file_checksum_sha256" => asset_file&.checksum_sha256,
      "policy_acknowledged_at" => policy_acknowledged_at&.iso8601,
    }
  end

  def co_host_sponsorships
    return [] if co_host_sponsorship_ids.blank?
    Sponsorship.where(id: co_host_sponsorship_ids, conference_id:)
  end

  def all_host_sponsorships
    ([sponsorship] + co_host_sponsorships).reject(&:withdrawn?)
  end

  private

  def set_conference_from_sponsorship
    self.conference_id ||= sponsorship&.conference_id
  end

  def generate_slug
    return if slug.present?
    return unless sponsorship&.organization

    sequence = sponsorship.sponsor_events.count + 1
    self.slug = "#{sponsorship.organization.domain}-#{sequence}"
  end

  def validate_co_host_sponsorship_ids
    return if co_host_sponsorship_ids.blank?

    invalid_ids = co_host_sponsorship_ids.reject do |id|
      Sponsorship.exists?(id:, conference_id:)
    end

    if invalid_ids.any?
      errors.add(:co_host_sponsorship_ids, "contains invalid sponsorship IDs: #{invalid_ids.join(', ')}")
    end
  end

  def validate_policy_acknowledged_on_create
    if policy_acknowledged_at.blank?
      errors.add(:policy_acknowledged_at, "must be acknowledged")
    end
  end
end

app/controllers/admin/sponsor_events_controller.rb
class Admin::SponsorEventsController < Admin::ApplicationController
  before_action :set_conference
  before_action :set_sponsor_event, only: %i(show edit update download_asset)

  def index
    @sponsor_events = @conference.sponsor_events
      .includes(:sponsorship)
      .order(status: :asc, starts_at: :asc)
  end

  def show
  end

  def edit
  end

  def download_asset
    asset = @sponsor_event.asset_file
    raise ActiveRecord::RecordNotFound unless asset
    redirect_to asset.download_url, allow_other_host: true
  end

  def update
    @sponsor_event.assign_attributes(sponsor_event_params)
    @sponsor_event.staff = current_staff

    if @sponsor_event.save
      ProcessSponsorEventEditJob.perform_later(@sponsor_event.last_editing_history)
      redirect_to conference_sponsor_event_path(@conference, @sponsor_event), notice: 'Event was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_conference
    @conference = Conference.find_by!(slug: params[:conference_slug])
    check_staff_conference_authorization!(@conference)
  end

  def set_sponsor_event
    @sponsor_event = @conference.sponsor_events.find(params[:id])
    @sponsorship = @sponsor_event.sponsorship
  end

  def sponsor_event_params
    params.require(:sponsor_event).permit(
      :title,
      :starts_at,
      :url,
      :price,
      :capacity,
      :location_en,
      :location_local,
      :slug,
      :status,
      :link_name,
      :admin_comment
    ).tap do |sp|
      if params[:sponsor_event][:co_host_sponsorship_ids].present?
        sp[:co_host_sponsorship_ids] = params[:sponsor_event][:co_host_sponsorship_ids]
          .split(',')
          .map(&:strip)
          .reject(&:blank?)
          .map(&:to_i)
      else
        sp[:co_host_sponsorship_ids] = []
      end
    end
  end
end

app/controllers/sponsor_events_controller.rb
class SponsorEventsController < ApplicationController
  include Rails.application.routes.url_helpers

  before_action :require_sponsorship_session
  before_action :require_event_submission_open, only: %i(new create edit update destroy)
  before_action :require_accepted_sponsorship
  before_action :set_sponsor_event, only: %i(show edit update destroy)

  def new
    @sponsor_event = current_sponsorship.sponsor_events.build
  end

  def create
    @sponsor_event = current_sponsorship.sponsor_events.build(sponsor_event_params)
    @sponsor_event.policy_acknowledged_at = Time.zone.now if params[:sponsor_event][:policy_agreement] == '1'
    assign_new_asset_file

    if @sponsor_event.save
      ProcessSponsorEventEditJob.perform_later(@sponsor_event.last_editing_history)
      redirect_to user_conference_sponsorship_event_path(conference: current_conference, id: @sponsor_event), notice: t('.notice')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
    unless @sponsor_event.editable_by_sponsor?
      redirect_to user_conference_sponsorship_event_path(conference: current_conference, id: @sponsor_event), alert: t('.withdrawn_not_editable')
    end
  end

  def update
    unless @sponsor_event.editable_by_sponsor?
      redirect_to user_conference_sponsorship_event_path(conference: current_conference, id: @sponsor_event), alert: t('.withdrawn_not_editable')
      return
    end

    success = ActiveRecord::Base.transaction do
      handle_asset_file_update
      unless @sponsor_event.update(sponsor_event_params)
        raise ActiveRecord::Rollback
      end
      true
    end

    if success
      ProcessSponsorEventEditJob.perform_later(@sponsor_event.last_editing_history)
      redirect_to user_conference_sponsorship_event_path(conference: current_conference, id: @sponsor_event), notice: t('.notice')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    unless @sponsor_event.editable_by_sponsor?
      redirect_to user_conference_sponsorship_event_path(conference: current_conference, id: @sponsor_event), alert: t('.withdrawn_not_editable')
      return
    end

    @sponsor_event.status = :withdrawn
    @sponsor_event.save!
    ProcessSponsorEventEditJob.perform_later(@sponsor_event.last_editing_history)
    redirect_to user_conference_sponsorship_path(conference: current_conference), notice: t('.notice')
  end

  private

  def require_event_submission_open
    unless current_conference&.event_submission_open?
      redirect_to user_conference_sponsorship_path(conference: current_conference), alert: t('sponsor_events.event_submission_not_open')
    end
  end

  def require_accepted_sponsorship
    unless current_sponsorship&.accepted?
      redirect_to user_conference_sponsorship_path(conference: current_conference), alert: t('sponsor_events.sponsorship_not_accepted')
    end
  end

  def set_sponsor_event
    @sponsor_event = current_sponsorship.sponsor_events.find(params[:id])
  end

  def assign_new_asset_file
    asset_file_id = params[:sponsor_event][:asset_file_id]
    return if asset_file_id.blank?

    asset_file = SponsorEventAssetFile
      .where(id: asset_file_id, sponsor_event: nil, sponsorship: current_sponsorship)
      .first!
    @sponsor_event.asset_file = asset_file
  end

  def handle_asset_file_update
    asset_file_id = params[:sponsor_event][:asset_file_id]

    if asset_file_id == ""
      @sponsor_event.asset_file&.destroy!
      @sponsor_event.reload_asset_file
    elsif asset_file_id.present? && asset_file_id.to_i != @sponsor_event.asset_file&.id
      new_file = SponsorEventAssetFile
        .where(id: asset_file_id, sponsor_event: nil, sponsorship: current_sponsorship)
        .first!
      @sponsor_event.asset_file&.destroy!
      @sponsor_event.asset_file = new_file
    end
  end

  def sponsor_event_params
    params.require(:sponsor_event).permit(
      :title,
      :starts_at,
      :url,
      :price,
      :capacity,
      :location_en,
      :location_local
    )
  end
end

app/views/admin/sponsor_events/_form.html.haml
= form_with(model: [@conference, sponsor_event], local: true) do |form|
  - if sponsor_event.errors.any?
    .alert.alert-danger
      %p #{sponsor_event.errors.count} error(s) prohibited this event from being saved:
      %ul
        - sponsor_event.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-6
      %h5 Event Details

      .form-group
        = form.label :title
        = form.text_field :title, class: 'form-control', required: true

      .form-group
        = form.label :slug
        = form.text_field :slug, class: 'form-control', required: true

      .form-group
        = form.label :starts_at
        = form.datetime_local_field :starts_at, class: 'form-control', required: true

      .form-group
        = form.label :url
        = form.url_field :url, class: 'form-control', required: true

      .form-group
        = form.label :price
        = form.text_field :price, class: 'form-control'

      .form-group
        = form.label :capacity
        = form.text_field :capacity, class: 'form-control'

      .form-group
        = form.label :location_en
        = form.text_field :location_en, class: 'form-control'

      .form-group
        = form.label :location_local
        = form.text_field :location_local, class: 'form-control'

    .col-md-6
      %h5 Admin Fields

      .form-group
        = form.label :status
        = form.select :status, SponsorEvent.statuses.keys.map { |s| [s.titleize, s] }, {}, class: 'form-control'

      .form-group
        = form.label :link_name
        %small.form-text.text-muted Display text for URL in published listing
        = form.text_field :link_name, class: 'form-control', placeholder: 'e.g., Registration, Details'

      .form-group
        = form.label :co_host_sponsorship_ids, 'Co-Host Sponsorship IDs'
        %small.form-text.text-muted Comma-separated sponsorship IDs for co-hosts
        = form.text_field :co_host_sponsorship_ids, class: 'form-control', value: sponsor_event.co_host_sponsorship_ids.join(', ')

      .form-group
        = form.label :admin_comment
        %small.form-text.text-muted Visible to sponsors
        = form.text_area :admin_comment, class: 'form-control', rows: 4

  .form-group.mt-4
    = form.submit 'Update Event', class: 'btn btn-primary'
    = link_to 'Cancel', conference_sponsor_event_path(@conference, sponsor_event), class: 'btn btn-secondary'

app/views/admin/sponsor_events/edit.html.haml
- content_for(:title) { t('.title') }

%nav{aria: {label: 'breadcrumb'}}
  %ol.breadcrumb
    %li.breadcrumb-item= link_to @conference.name, conference_path(@conference)
    %li.breadcrumb-item= link_to @sponsorship.name, conference_sponsorship_path(@conference, @sponsorship)
    %li.breadcrumb-item= link_to @sponsor_event.title, conference_sponsor_event_path(@conference, @sponsor_event)
    %li.breadcrumb-item.active{aria: {current: 'page'}} Edit

%h3 Edit Event

= render 'form', sponsor_event: @sponsor_event

app/views/admin/sponsor_events/index.html.haml
- content_for(:title) { t('.title') }

%nav{aria: {label: 'breadcrumb'}}
  %ol.breadcrumb
    %li.breadcrumb-item= link_to @conference.name, conference_path(@conference)
    %li.breadcrumb-item.active{aria: {current: 'page'}} Events

%h3 Sponsor Events

- if @sponsor_events.empty?
  %p.text-muted No events submitted yet.
- else
  - SponsorEvent.statuses.keys.each do |status|
    - events_in_status = @sponsor_events.select { |e| e.status == status }
    - next if events_in_status.empty?

    %h5.mt-4
      - case status
      - when 'pending'
        %span.badge.badge-warning= status.titleize
      - when 'accepted'
        %span.badge.badge-success= status.titleize
      - when 'rejected'
        %span.badge.badge-danger= status.titleize
      - when 'withdrawn'
        %span.badge.badge-secondary= status.titleize

    .row.py-2
      - events_in_status.sort_by(&:starts_at).each do |event|
        .col-md-6.mb-3
          .card
            .card-body
              %h5.card-title
                = link_to event.title, conference_sponsor_event_path(@conference, event)
              %dl.row.mb-2
                %dt.col-sm-4 Date/Time
                %dd.col-sm-8= l(event.starts_at, format: :long)

                %dt.col-sm-4 Price
                %dd.col-sm-8= event.price.presence || 'Free'

                %dt.col-sm-4 Capacity
                %dd.col-sm-8= event.capacity.present? ? event.capacity : '-'

                - if event.location_en.present? || event.location_local.present?
                  %dt.col-sm-4 Location
                  %dd.col-sm-8
                    = event.location_en
                    - if event.location_local.present? && event.location_local != event.location_en
                      %br
                      %small.text-muted= event.location_local

                %dt.col-sm-4 Host
                %dd.col-sm-8
                  - event.all_host_sponsorships.each_with_index do |s, i|
                    - if i > 0
                      ,
                    = link_to s.name, conference_sponsorship_path(@conference, s)

                %dt.col-sm-4 URL
                %dd.col-sm-8
                  = link_to (event.link_name.presence || 'Link'), event.url, target: '_blank', rel: 'noopener'

              .btn-group
                = link_to 'View', conference_sponsor_event_path(@conference, event), class: 'btn btn-sm btn-secondary'
                = link_to 'Edit', edit_conference_sponsor_event_path(@conference, event), class: 'btn btn-sm btn-primary'

app/views/admin/sponsor_events/show.html.haml
- content_for(:title) { t('.title', event: @sponsor_event.title) }

%nav{aria: {label: 'breadcrumb'}}
  %ol.breadcrumb
    %li.breadcrumb-item= link_to @conference.name, conference_path(@conference)
    %li.breadcrumb-item= link_to @sponsorship.name, conference_sponsorship_path(@conference, @sponsorship)
    %li.breadcrumb-item.active{aria: {current: 'page'}}= @sponsor_event.title

.d-md-flex.justify-content-between
  %h3= @sponsor_event.title
  %div
    = link_to 'Edit', edit_conference_sponsor_event_path(@conference, @sponsor_event), class: 'btn btn-primary'
    = link_to 'History', conference_sponsor_event_editing_histories_path(@conference, @sponsor_event), class: 'btn btn-secondary'

.row.mt-3
  .col-md-8
    .card
      %h5.card-header Event Details
      .card-body
        %dl
          .row
            %dt.col-sm-3 Title
            %dd.col-sm-9= @sponsor_event.title

          .row
            %dt.col-sm-3 Slug
            %dd.col-sm-9
              %code= @sponsor_event.slug

          .row
            %dt.col-sm-3 Starts At
            %dd.col-sm-9= l(@sponsor_event.starts_at, format: :long)

          .row
            %dt.col-sm-3 URL
            %dd.col-sm-9
              = link_to @sponsor_event.url, @sponsor_event.url, target: '_blank'

          .row
            %dt.col-sm-3 Price
            %dd.col-sm-9= @sponsor_event.price.presence || '-'

          .row
            %dt.col-sm-3 Capacity
            %dd.col-sm-9= @sponsor_event.capacity.presence || '-'

          .row
            %dt.col-sm-3 Location (EN)
            %dd.col-sm-9= @sponsor_event.location_en.presence || '-'

          .row
            %dt.col-sm-3 Location (Local)
            %dd.col-sm-9= @sponsor_event.location_local.presence || '-'

          .row
            %dt.col-sm-3 Link Name
            %dd.col-sm-9= @sponsor_event.link_name.presence || '-'

          .row
            %dt.col-sm-3 Hero Image
            %dd.col-sm-9
              - if @sponsor_event.asset_file
                = link_to 'Download', download_asset_conference_sponsor_event_path(@conference, @sponsor_event)
              - else
                \-

  .col-md-4
    .card
      %h5.card-header Status
      .card-body
        %p.card-text
          - case @sponsor_event.status
          - when 'pending'
            %span.badge.badge-warning Pending
          - when 'accepted'
            %span.badge.badge-success Accepted
          - when 'rejected'
            %span.badge.badge-danger Rejected
          - when 'withdrawn'
            %span.badge.badge-secondary Withdrawn

        %p.card-text
          %strong Policy Acknowledged:
          - if @sponsor_event.policy_acknowledged_at
            = l(@sponsor_event.policy_acknowledged_at, format: :short)
          - else
            Not acknowledged

    .card.mt-2
      %h5.card-header Sponsorship
      .card-body
        %p.card-text
          = link_to @sponsorship.name, conference_sponsorship_path(@conference, @sponsorship)

    - if @sponsor_event.co_host_sponsorship_ids.present?
      .card.mt-2
        %h5.card-header Co-Hosts
        %ul.list-group.list-group-flush
          - @sponsor_event.co_host_sponsorships.each do |co_host|
            %li.list-group-item
              = link_to co_host.name, conference_sponsorship_path(@conference, co_host)
              - if co_host.withdrawn?
                %span.badge.badge-secondary withdrawn

    - if @sponsor_event.admin_comment.present?
      .card.mt-2
        %h5.card-header Admin Comment
        .card-body
          %p.card-text
            - @sponsor_event.admin_comment.each_line do |l|
              = l
              %br