config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  scope path: 'admin', module: 'admin' do
    get '/' => 'dashboard#index', as: :dashboard
    get '/slacktown' => 'dashboard#slacktown', as: :slacktown
    get '/mailtown' => 'dashboard#mailtown', as: :mailtown
    get '/errortown' => 'dashboard#errortown', as: :errortown

    resources :conferences, param: :slug do
      member do
        get :attendees_keeper
        get :sponsors_yml
        get :sponsors_json
        get :asset_urls
        get :table_view
      end

      resource :booth_assignment, only: %i(show update)

      resources :form_descriptions, param: :locale, except: %i(index)
      resources :plans, except: %i(show)

      resources :sponsorships, except: %i(index new create) do
        resources :sponsorship_editing_histories, as: :editing_histories, path: 'editing_history', only: %i(index)
        resources :sponsorship_staff_notes, as: :staff_notes, path: 'staff_notes', only: %i(index create edit update destroy)
        resource :impersonation, only: %i(create), controller: 'sponsorship_impersonations'
        member do
          get :download_asset
        end
      end

      resources :sponsor_events, path: 'events', except: %i(new create destroy) do
        resources :sponsor_event_editing_histories, as: :editing_histories, path: 'editing_history', only: %i(index)
        member do
          get :download_asset
        end
      end

      resources :announcements
      resources :broadcasts do
        resources :broadcast_deliveries, as: :deliveries, path: 'deliveries', only: %i(create destroy)
        member do
          post :dispatch_delivery
        end
      end
    end

    resources :organizations, param: :slug, only: %i(index new create show edit update), constraints: {slug: /[^\/]+/}

    resource :session, only: %i(new destroy) do
      get :rise, as: :rise
    end
  end

  get '/auth/:provider/callback' => 'admin/sessions#create'

  get '/' => 'root#index'

  scope as: :user do
    resource :session, only: %i(new create destroy) do
      get 'claim/:handle', action: :claim, as: :claim
    end

    resources :conferences, param: :slug, only: %i(index) do
      resource :sponsorship, only: %i(new create show edit update) do
        resources :broadcasts, only: %i(index)
        resource :exhibition, only: %i(new create edit update)
        resources :events, controller: 'sponsor_events', only: %i(new create show edit update destroy)
        resources :pass_redemptions, only: %i(index) do
          member do
            resource :retraction, only: %i(new create show), controller: 'pass_retractions'
          end
        end
      end
      resources :sponsorship_asset_files, only: %i(create update show) do
        member do
          post :initiate_update
        end
      end
      resources :event_asset_files, controller: 'sponsor_event_asset_files', only: %i(create update show) do
        member do
          post :initiate_update
        end
      end
    end


    post '/webhooks/mailgun' => 'webhooks/mailgun#webhook'
  end


  get '/site/sha' => RevisionPlate::App.new(File.join(__dir__, '..', 'REVISION'))
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conference.rb
class Conference < ApplicationRecord
  GithubRepo = Struct.new(:raw, :name, :path, :branch, keyword_init: true) do
    def to_s
      raw
    end
  end

  has_many :form_descriptions, dependent: :destroy
  has_many :plans, -> { order(rank: :asc) }, dependent: :destroy
  has_many :sponsorships, dependent: :destroy
  has_many :sponsor_events, dependent: :destroy
  has_many :announcements, dependent: :destroy
  has_many :broadcasts, dependent: :destroy

  scope :application_open, -> { t = Time.now; where('application_opens_at <= ? AND (application_closes_at > ? OR application_closes_at IS NULL) AND application_opens_at IS NOT NULL', t, t) }
  scope :amendment_open, -> { t = Time.now; where('application_opens_at <= ? AND (amendment_closes_at > ? OR amendment_closes_at IS NULL) AND application_opens_at IS NOT NULL', t, t) }
  scope :publicly_visible, -> { where(hidden: false) }

  validates :name, presence: true
  validates :slug, presence: true, uniqueness: true
  validates :contact_email_address, presence: true
  validates :tito_slug, format: { with: %r{\A[^/]+/[^/]+\z}, message: "must be :account_slug/:event_slug", allow_blank: true }
  validate :validate_valid_github_repo

  before_validation :generate_slug
  before_validation :generate_reception_key
  before_validation :generate_invite_code

  def to_param
    slug
  end

  def application_open?
    t = Time.now
    application_opens_at && application_opens_at <= t && (!application_closes_at || t < application_closes_at)
  end

  def amendment_open?
    t = Time.now
    application_opens_at && application_opens_at <= t && (!amendment_closes_at || t < amendment_closes_at)
  end

  def distributing_ticket?
    t = Time.now
    ticket_distribution_starts_at && ticket_distribution_starts_at <= t
  end

  def pass_retraction_enabled?
    t = Time.now
    pass_retraction_disables_at.nil? || t < pass_retraction_disables_at
  end

  def event_submission_open?
    t = Time.now
    event_submission_starts_at && event_submission_starts_at <= t
  end

  def form_description_for_locale
    form_descriptions.find_by(locale: I18n.locale) || form_descriptions.find_by!(locale: 'en')
  end

  def github_repo
    ghr = read_attribute(:github_repo)
    if @github_repo&.raw != ghr
      m = ghr.match(/^(.+?)(?:@(.+?))?(?::(.+?))$/)
      @github_repo = m && GithubRepo.new(
        raw: ghr,
        name: m[1],
        branch: m[2].presence,
        path: m[3].presence,
      )
    end
    @github_repo
  end

  def validate_valid_github_repo
    return unless read_attribute(:github_repo).present?
    unless github_repo && github_repo.name.present? && github_repo.path.present?
      errors.add :github_repo, :invalid
    end
  end

  def verify_invite_code(code)
    return true unless hidden?
    !code.blank? && Rack::Utils.secure_compare(code, invite_code)
  end

  private def generate_slug
    self.slug = name.remove(' ').parameterize if slug.blank?
  end

  # NOTE: Reception functionality removed; this method kept for historical data preservation.
  # The reception_key column has a NOT NULL constraint and contains historical data.
  private def generate_reception_key
    self.reception_key ||= SecureRandom.urlsafe_base64(96)
  end

  private def generate_invite_code
    if self.hidden?
      self.invite_code ||= SecureRandom.urlsafe_base64(48)
    end
  end
end

app/controllers/admin/conferences_controller.rb
class Admin::ConferencesController < Admin::ApplicationController
  before_action :require_unrestricted_staff, only: [:index, :new, :create]
  before_action :set_conference, only: [:show, :edit, :update, :destroy, :attendees_keeper, :sponsors_yml, :sponsors_json, :asset_urls, :table_view]

  def index
    @conferences = Conference.all
  end

  def show
    @plans_with_count = @conference
      .plans
      .left_joins(:sponsorships)
      .group(:id)
      .select('plans.*, COUNT(sponsorships.plan_id) as cnt')
      .map {|_| [_, _.cnt, _.capacity] }
      .sort_by { |plan, _cnt, _capa| plan.rank }
  end

  def attendees_keeper
  end

  def sponsors_yml
    render plain: GenerateSponsorsYamlFileJob.new(@conference, push: false).tap(&:perform_now).yaml_data
  end

  def sponsors_json
    render plain: GenerateSponsorsYamlFileJob.new(@conference, push: false).tap(&:perform_now).json_data
  end

  def table_view
    @sponsorships = @conference.sponsorships
      .includes_contacts
      .includes_requests
  end

  def asset_urls
    render json: {
      files: @conference.sponsorships.includes(:asset_file).map(&:asset_file).compact.map do |asset|
        [asset.filename, asset.download_url]
      end,
    }.to_json
  end

  def new
    @conference = Conference.new
  end

  def edit
  end

  def create
    @conference = Conference.new(conference_params)

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @conference.assign_attributes(conference_params)
    @conference.allow_restricted_access = true if current_staff.restricted_repos
    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @conference.destroy
    respond_to do |format|
      format.html { redirect_to _conferences_url, notice: 'Conference was successfully destroyed.' }
    end
  end

  private

  def set_conference
    @conference = Conference.find_by!(slug: params[:slug])
    check_staff_conference_authorization!(@conference)
  end

  def conference_params
    params.require(:conference).permit(
      :name,
      :slug,
      :application_opens_at,
      :application_closes_at,
      :ticket_distribution_starts_at,
      :pass_retraction_disables_at,
      :amendment_closes_at,
      :event_submission_starts_at,
      :booth_capacity,
      :contact_email_address,
      :additional_attendees_registration_open,
      :github_repo,
      :github_repo_images_path,
      :tito_slug,
      :tito_booth_paid_flat_discount_amount,
      :hidden,
      :no_plan_allowed,
      :allow_restricted_access,
    )
  end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  def index
    @conferences = Conference.application_open.publicly_visible.order(id: :asc)

    if @conferences.one?
      redirect_to user_conference_sponsorship_path(@conferences.first)
    end
  end
end

app/views/admin/conferences/_form.html.haml
= form_with(model: conference, local: true) do |form|
  - if conference.errors.any?
    .alert.alert-danger
      %p #{pluralize(conference.errors.count, "error")} prohibited this from being saved:
      %ul
        - conference.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :name
    = form.text_field :name, class: 'form-control', required: true
  .form-group
    = form.label :slug
    = form.text_field :slug, class: 'form-control', required: true
  .form-group
    = form.label :contact_email_address
    = form.email_field :contact_email_address, class: 'form-control', required: true
  .form-group
    = form.label :github_repo
    = form.text_field :github_repo, class: 'form-control'
    %small.form-text
      %code owner/repo[@branch]:path/to/file
  .form-group
    = form.label :github_repo_images_path
    = form.text_field :github_repo_images_path, class: 'form-control'
    %small.form-text
      Path prefix for event asset images within the GitHub repo, without trailing slash (e.g.
      %code images
      )
  .form-group
    = form.label :tito_slug
    = form.text_field :tito_slug, class: 'form-control'
    %small.form-text
      %code account_slug/event_slug
  .form-group
    = form.label :tito_booth_paid_flat_discount_amount
    = form.number_field :tito_booth_paid_flat_discount_amount, class: 'form-control', step: '0.01'
  .form-group
    = form.label :application_opens_at
    .input-group
      = form.datetime_local_field :application_opens_at, class: 'form-control', step: 1
      .input-group-append
        %button.btn.btn-outline-secondary{type: 'button', commandfor: 'conference_application_opens_at', command: '--set-now'} Now
  .form-group
    = form.label :application_closes_at
    .input-group
      = form.datetime_local_field :application_closes_at, class: 'form-control', step: 1
      .input-group-append
        %button.btn.btn-outline-secondary{type: 'button', commandfor: 'conference_application_closes_at', command: '--set-now'} Now
  .form-group
    = form.label :amendment_closes_at
    .input-group
      = form.datetime_local_field :amendment_closes_at, class: 'form-control', step: 1
      .input-group-append
        %button.btn.btn-outline-secondary{type: 'button', commandfor: 'conference_amendment_closes_at', command: '--set-now'} Now
  .form-group
    = form.label :event_submission_starts_at
    .input-group
      = form.datetime_local_field :event_submission_starts_at, class: 'form-control', step: 1
      .input-group-append
        %button.btn.btn-outline-secondary{type: 'button', commandfor: 'conference_event_submission_starts_at', command: '--set-now'} Now
  .form-group
    = form.label :ticket_distribution_starts_at
    .input-group
      = form.datetime_local_field :ticket_distribution_starts_at, class: 'form-control', step: 1
      .input-group-append
        %button.btn.btn-outline-secondary{type: 'button', commandfor: 'conference_ticket_distribution_starts_at', command: '--set-now'} Now
  .form-group
    = form.label :pass_retraction_disables_at
    .input-group
      = form.datetime_local_field :pass_retraction_disables_at, class: 'form-control', step: 1
      .input-group-append
        %button.btn.btn-outline-secondary{type: 'button', commandfor: 'conference_pass_retraction_disables_at', command: '--set-now'} Now
  .form-group
    = form.label :booth_capacity
    = form.number_field :booth_capacity, class: 'form-control'
    %small.form-text
      %code must be 1+ to activate booth request form

  .form-group
    .form-check
      = form.check_box :additional_attendees_registration_open, class: 'form-check-input'
      = form.label :additional_attendees_registration_open, class: 'form-check-label'

  .form-group
    .form-check
      = form.check_box :hidden, class: 'form-check-input'
      = form.label :hidden, class: 'form-check-label'

  .form-group
    .form-check
      = form.check_box :no_plan_allowed, class: 'form-check-input'
      = form.label :no_plan_allowed, class: 'form-check-label'

  .form-group
    .form-check
      = form.check_box :allow_restricted_access, class: 'form-check-input'
      = form.label :allow_restricted_access, class: 'form-check-label'

  .form-group
    = form.submit class: 'btn btn-primary'

app/views/admin/conferences/attendees_keeper.html.haml
- content_for(:title) { t('.title') }

%nav{aria: {label: 'breadcrumb'}}
  %ol.breadcrumb
    %li.breadcrumb-item= link_to @conference.name, conference_path(@conference)
    %li.breadcrumb-item.active{aria: {current: 'page'}} Attendees Keeper

.d-md-flex.justify-content-between
  %h3 Attendees Keeper

- sponsorships = @conference.sponsorships.active.includes(:plan).to_a.sort_by{|_| -_.total_number_of_attendees }

%ul
  %li
    Sponsorship Attendees Total: #{sponsorships.map(&:total_number_of_attendees).inject(:+)}
    %ul
      %li Included: #{sponsorships.map {|_| _.plan&.number_of_guests }.compact.inject(:+)}
      %li Additionally Sold: #{sponsorships.map(&:number_of_additional_attendees).compact.inject(:+)}
.row
  .col-12
    .card
      .card-header Table
      %table.card-body.table.table-hover.text-right
        %thead
          %tr
            %th.text-left{scope: :col} Sponsorship
            %th{scope: :col} Total
            %th{scope: :col} Included
            %th{scope: :col} Additional
        %tbody
          - sponsorships.each do |sponsorship|
            %tr
              %td.text-left= link_to sponsorship.name, conference_sponsorship_path(@conference, sponsorship)
              %td= sponsorship.total_number_of_attendees
              %td= sponsorship.plan&.number_of_guests || 0
              %td= sponsorship.number_of_additional_attendees || 0

app/views/admin/conferences/edit.html.haml
- content_for(:title) { t('.title') }

%h1 Editing Conference

= render 'form', conference: @conference

app/views/admin/conferences/index.html.haml
- content_for(:title) { t('.title') }

%h1 Listing conferences

= link_to 'New', new_conference_path, class: 'btn btn-default'

.row.py-2
  - @conferences.each do |conference|
    .col-md-6
      .card
        .card-body
          = link_to conference.name, conference

app/views/admin/conferences/new.html.haml
- content_for(:title) { t('.title') }

%h1 New Conference

= render 'form', conference: @conference

app/views/admin/conferences/show.html.haml
- content_for(:title) { t('.title', conference: @conference.name) }

%p
  - application_form_url = new_user_conference_sponsorship_url(@conference, {invite_code: @conference.invite_code}.compact)

.d-md-flex.justify-content-between
  %h2 Conference: #{@conference.name}
  %div
    = link_to 'Edit', edit_conference_path(@conference), class: 'btn btn-primary'
    = link_to 'Preview', application_form_url, class: 'btn btn-secondary'


.row.my-3
  .col-md-4
    .card
      .card-body
        %p.card-text
          %strong Name:
          = @conference.name
        %p.card-text
          %strong Slug:
          = @conference.slug
        %p.card-text
          %strong Application opens:
          = @conference.application_opens_at
          til
          = @conference.application_closes_at
        %p.card-text
          %strong Accepting amendment closes:
          = @conference.amendment_closes_at
        - if @conference.hidden?
          %p.card-text
            %strong Form URL:
            = link_to application_form_url, application_form_url

  .col-md-4
    .card
      %h5.card-header
        Form Descriptions
      .card-body
        %ul
          - @conference.form_descriptions.select(:id, :locale).each do |desc|
            %li= link_to desc.locale, [@conference, desc]
        = link_to 'Add locale', new_conference_form_description_path(@conference), class: 'card-link'
    .card.mt-2
      %h5.card-header
        Plans
      .card-body
        %ul
          - @plans_with_count.each do |plan, count, capacity|
            %li
              = link_to plan.name, edit_conference_plan_path(@conference, plan)
              %span (#{count}/#{capacity})
        = link_to 'View all plans', conference_plans_path(@conference), class: 'card-link'
        = link_to 'Add plan', new_conference_plan_path(@conference), class: 'card-link'

  .col-md-4
    .card
      %h5.card-header
        Operations
      .card-body
        %ul
          %li= link_to "Announcements", conference_announcements_path(@conference)
          %li= link_to "Broadcasts", conference_broadcasts_path(@conference)
          %li= link_to "Check Attendees", attendees_keeper_conference_path(@conference)
          %li= link_to "Booth Assignment", conference_booth_assignment_path(@conference)
          %li= link_to "Events", conference_sponsor_events_path(@conference)

.row
  .col-md-12
    .card
      %h5.card-header
        Sponsorships
      .card-body
        - @conference.sponsorships.where(withdrawn_at: nil).includes(:plan).order(id: :asc).group_by(&:plan).sort_by {|p, _| p&.rank || 9999 }.each do |plan, sponsorships|
          %h6
            = plan&.name || 'Undetermined'
            %span (#{sponsorships.size}/#{plan&.capacity})
          %ul
            - sponsorships.sort_by(&:id).each do |sponsorship|
              %li
                - case
                - when sponsorship.customization_name.present?
                  #{sponsorship.customization_name}:
                = link_to sponsorship.name, [@conference, sponsorship]

                - if sponsorship.exhibitor?
                  %span.badge.badge-info Booth
                - if sponsorship.customization_planned?
                  %span.badge.badge-warning Custom Plan: Tentative
                - if !sponsorship.accepted?
                  %span.badge.badge-warning Not Accepted
                - if sponsorship.suspended?
                  %span.badge.badge-danger Suspended


        - @conference.sponsorships.withdrawn.tap do |sponsorships|
          %h6
            Withdrawn
          %ul
            - sponsorships.sort_by(&:id).each do |sponsorship|
              %li.text-muted
                - case
                - when sponsorship.customization_name.present?
                  #{sponsorship.customization_name}:
                = link_to sponsorship.name, [@conference, sponsorship]

app/views/admin/conferences/table_view.html.haml
- content_for(:title) { t('.title') }

%nav{aria: {label: 'breadcrumb'}}
  %ol.breadcrumb
    %li.breadcrumb-item= link_to @conference.name, conference_path(@conference)
    %li.breadcrumb-item.active{aria: {current: 'page'}} Table View

.d-md-flex.justify-content-between
  %h3 Table View

.row
  .col-12
    .card.responsive-table
      .card-header Table
      %table.card-body.table.table-hover.table-small{style: 'table-layout: fixed;'}
        %thead
          %tr
            %th{scope: :col, style: 'width: 150px;'} Sponsorship
            %th{scope: :col, style: 'width: 80px;'} Plan
            %th{scope: :col, style: 'width: 100px;'} Displayed Plan
            %th{scope: :col, style: 'width: 200px;'} Billing Request
            %th{scope: :col, style: 'width: 200px;'} Customization Request
            %th{scope: :col, style: 'width: 200px;'} Note
        %tbody
          - @sponsorships.each do |sponsorship|
            %tr
              %td.text-truncate.text-left= link_to sponsorship.name, conference_sponsorship_path(@conference, sponsorship)
              %td= sponsorship.plan&.name
              %td= sponsorship.plan_name
              %td= sponsorship.billing_request&.body
              %td= sponsorship.customization_request&.body
              %td= sponsorship.note&.body