config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  scope path: 'admin', module: 'admin' do
    get '/' => 'dashboard#index', as: :dashboard
    get '/slacktown' => 'dashboard#slacktown', as: :slacktown
    get '/mailtown' => 'dashboard#mailtown', as: :mailtown
    get '/errortown' => 'dashboard#errortown', as: :errortown

    resources :conferences, param: :slug do
      member do
        get :attendees_keeper
        get :sponsors_yml
        get :sponsors_json
        get :asset_urls
        get :table_view
      end

      resource :booth_assignment, only: %i(show update)

      resources :form_descriptions, param: :locale, except: %i(index)
      resources :plans, except: %i(show)

      resources :sponsorships, except: %i(index new create) do
        resources :sponsorship_editing_histories, as: :editing_histories, path: 'editing_history', only: %i(index)
        resources :sponsorship_staff_notes, as: :staff_notes, path: 'staff_notes', only: %i(index create edit update destroy)
        resource :impersonation, only: %i(create), controller: 'sponsorship_impersonations'
        member do
          get :download_asset
        end
      end

      resources :sponsor_events, path: 'events', except: %i(new create destroy) do
        resources :sponsor_event_editing_histories, as: :editing_histories, path: 'editing_history', only: %i(index)
        member do
          get :download_asset
        end
      end

      resources :announcements
      resources :broadcasts do
        resources :broadcast_deliveries, as: :deliveries, path: 'deliveries', only: %i(create destroy)
        member do
          post :dispatch_delivery
        end
      end
    end

    resources :organizations, param: :slug, only: %i(index new create show edit update), constraints: {slug: /[^\/]+/}

    resource :session, only: %i(new destroy) do
      get :rise, as: :rise
    end
  end

  get '/auth/:provider/callback' => 'admin/sessions#create'

  get '/' => 'root#index'

  scope as: :user do
    resource :session, only: %i(new create destroy) do
      get 'claim/:handle', action: :claim, as: :claim
    end

    resources :conferences, param: :slug, only: %i(index) do
      resource :sponsorship, only: %i(new create show edit update) do
        resources :broadcasts, only: %i(index)
        resource :exhibition, only: %i(new create edit update)
        resources :events, controller: 'sponsor_events', only: %i(new create show edit update destroy)
        resources :pass_redemptions, only: %i(index) do
          member do
            resource :retraction, only: %i(new create show), controller: 'pass_retractions'
          end
        end
      end
      resources :sponsorship_asset_files, only: %i(create update show) do
        member do
          post :initiate_update
        end
      end
      resources :event_asset_files, controller: 'sponsor_event_asset_files', only: %i(create update show) do
        member do
          post :initiate_update
        end
      end
    end


    post '/webhooks/mailgun' => 'webhooks/mailgun#webhook'
  end


  get '/site/sha' => RevisionPlate::App.new(File.join(__dir__, '..', 'REVISION'))
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/sponsorships_controller.rb
class Admin::SponsorshipsController < Admin::ApplicationController
  before_action :set_conference
  before_action :set_sponsorship

  def show
    @pinned_staff_notes = @sponsorship.staff_notes.where('stickiness > 0').order(stickiness: :desc, created_at: :desc).includes(:staff)
    @staff_notes = @sponsorship.staff_notes.where('stickiness = 0').order(stickiness: :desc, created_at: :desc).includes(:staff).limit(5)
    @new_staff_note = SponsorshipStaffNote.new(sponsorship: @sponsorship)
  end

  def download_asset
    asset = @sponsorship.asset_file
    raise ActiveRecord::RecordNotFound unless asset
    redirect_to(asset.download_url(), allow_other_host: true)
  end

  def edit
    @sponsorship.build_alternate_billing_contact unless @sponsorship.alternate_billing_contact
    @sponsorship.build_billing_request unless @sponsorship.billing_request
    @sponsorship.build_customization_request unless @sponsorship.customization_request
    @sponsorship.build_note unless @sponsorship.note
  end

  def update
    @sponsorship.assign_attributes(sponsorship_params)
    @sponsorship.staff = current_staff
    respond_to do |format|
      if @sponsorship.save
        ProcessSponsorshipEditJob.perform_later(@sponsorship.last_editing_history)
        format.html { redirect_to conference_sponsorship_path(@conference, @sponsorship), notice: 'Sponsorship was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    return render(status: 404, plain: '') if @sponsorship.withdrawn?
    @sponsorship.staff = current_staff
    respond_to do |format|
      @sponsorship.withdraw
      @sponsorship.save!
      ProcessSponsorshipEditJob.perform_later(@sponsorship.last_editing_history)
      format.html { redirect_to conference_sponsorship_path(@conference, @sponsorship), notice: 'Sponsorship was successfully withdrawn.' }
    end
  end

  private

  def sponsorship_params
    params.require(:sponsorship).permit(
      :plan_id,
      :name,
      :url,
      :profile,
      :logo_key,
      :booth_requested,
      :fallback_option,

      :customization,
      :customization_name,
      :booth_assigned,

      :suspended,
      :accepted,

      :number_of_additional_attendees,

      contact_attributes: %i(id email email_cc address organization unit name),
      alternate_billing_contact_attributes: %i(_keep id email address organization unit name),

      billing_request_attributes: %i(id body),
      customization_request_attributes: %i(id body),
      note_attributes: %i(id body),
    ).tap do |sp|
      unless sp[:alternate_billing_contact_attributes].nil? || sp[:alternate_billing_contact_attributes][:_keep] == '1'
        (sp[:alternate_billing_contact_attributes] ||= {})[:_destroy] = '1'
      end
      %i(
        billing_request_attributes
        customization_request_attributes
        note_attributes
      ).each do |k|
        unless sp.dig(k, :body).present?
          sp[k][:_destroy] = '1' if sp[k]
        end
      end
    end
  end

  def set_conference
    @conference = Conference.find_by!(slug: params[:conference_slug])
    check_staff_conference_authorization!(@conference)
  end

  def set_sponsorship
    @sponsorship = Sponsorship.where(conference: @conference).find(params[:id])
  end
end

app/controllers/sponsorships_controller.rb
class SponsorshipsController < ApplicationController
  def show
    unless current_sponsorship
      return redirect_to new_user_conference_sponsorship_path(conference: @conference)
    end
    @sponsorship = current_sponsorship
    @conference = current_sponsorship&.conference
    raise ActiveRecord::RecordNotFound unless @conference

    @announcements = @sponsorship.conference.announcements
      .where(locale: I18n.locale)
      .where('published_at IS NOT NULL')
      .order('stickiness DESC, id DESC')
      .merge(@sponsorship.exhibitor? ? Announcement.for_exhibitors : Announcement.for_sponsors)
  end

  def edit
    @sponsorship = current_sponsorship
    @conference = current_sponsorship&.conference
    raise ActiveRecord::RecordNotFound if !@conference&.amendment_open? && !current_staff

    @sponsorship.build_nested_attributes_associations
  end

  def new
    return render(status: 404, plain: '404') if current_sponsorship

    @conference = Conference.find_by!(slug: params[:conference_slug])
    return render(plain: '404', status: 404) unless @conference.verify_invite_code(params[:invite_code])
    return render(:closed, status: 403) if !@conference&.application_open? && !current_staff

    @affiliated_organization = Organization.find_by_affiliation_code(params[:affiliation])

    @sponsorship = Sponsorship.new(copied_sponsorship_attributes)
    @sponsorship.conference = @conference
    @sponsorship.build_nested_attributes_associations
  end

  def create
    return render(status: 404, plain: '404') if current_sponsorship

    @conference = Conference.find_by!(slug: params[:conference_slug])
    return render(plain: '404', status: 404) unless @conference.verify_invite_code(params[:invite_code])
    return render(:closed, status: 403) if !@conference&.application_open? && !current_staff

    @sponsorship = Sponsorship.new(sponsorship_params.except(:asset_file_id))

    if sponsorship_params[:asset_file_id].present? 
      asset_src = SponsorshipAssetFile
        .available_for_user(
          sponsorship_params[:asset_file_id],
          session_asset_file_ids: session[:asset_file_ids],
          available_sponsorship_ids: current_available_sponsorships&.pluck(:id) || [],
        )
        .first
      return render(plain: '404 asset not found', status: 404) unless asset_src
      if asset_src.sponsorship_id.present?
        new_asset = asset_src.copy_to!(@conference)
        (session[:asset_file_ids] ||= []) << new_asset.id
        @sponsorship.asset_file = new_asset
      else
        @sponsorship.asset_file = asset_src
      end
    end

    @sponsorship.locale = I18n.locale
    @sponsorship.conference = @conference
    affiliated_organization = Organization.find_by_affiliation_code(params[:affiliation])
    @sponsorship.assume_organization(affiliated_organization:)
    @sponsorship.accept if @sponsorship.plan&.auto_acceptance && !@sponsorship.organization&.auto_acceptance_disabled

    respond_to do |format|
      if @sponsorship.save(context: :update_by_user)
        (session[:sponsorship_ids] ||= []).unshift @sponsorship.id
        session[:asset_file_ids]&.delete(@sponsorship.asset_file.id)
        SponsorshipWelcomeJob.perform_later(@sponsorship)
        format.html { redirect_to user_conference_sponsorship_path(conference: @conference), notice: t('.notice') }
      else
        @sponsorship.build_nested_attributes_associations
        format.html { render :new }
      end
    end
  end

  def update
    @sponsorship = current_sponsorship
    @conference = current_sponsorship&.conference
    raise ActiveRecord::RecordNotFound unless @conference&.amendment_open?

    sp = sponsorship_params
    sp.delete(:asset_file_id) if @sponsorship.asset_file_id
    @sponsorship.assign_attributes(sp)
    @sponsorship.locale = I18n.locale

    respond_to do |format|
      if @sponsorship.save(context: :update_by_user)
        ProcessSponsorshipEditJob.perform_later(@sponsorship.last_editing_history)
        format.html { redirect_to user_conference_sponsorship_path(conference: @conference), notice: 'Your application was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def sponsorship_params
    params.require(:sponsorship).permit(
      :plan_id,
      :name,
      :url,
      :profile,
      :asset_file_id,
      :asset_file_id_to_copy,
      :booth_requested,
      :fallback_option,
      :number_of_additional_attendees,
      contact_attributes: %i(id email email_cc address organization unit name),
      alternate_billing_contact_attributes: %i(_keep id email address organization unit name),
      billing_request_attributes: %i(id body),
      customization_request_attributes: %i(id body),
      note_attributes: %i(id body),
    ).tap do |sp|
      unless sp[:alternate_billing_contact_attributes].nil? || sp[:alternate_billing_contact_attributes][:_keep] == '1'
        (sp[:alternate_billing_contact_attributes] ||= {})[:_destroy] = '1'
      end
      %i(
        billing_request_attributes
        customization_request_attributes
        note_attributes
      ).each do |k|
        unless sp.dig(k, :body).present?
          sp[k][:_destroy] = '1' if sp[k]
        end
      end
    end
  end

  def copied_sponsorship_attributes
    return {} unless params[:sponsorship_id_to_copy].present?
    return {} unless session[:sponsorship_ids]&.include?(params[:sponsorship_id_to_copy].to_i)
    src = Sponsorship.find_by(id: params[:sponsorship_id_to_copy])
    return {} unless src
    src.attributes_for_copy
  end
end

app/helpers/admin/sponsorships_helper.rb
module Admin::SponsorshipsHelper
  def front_mail_to_link(to, from: nil, cc: [])
    base = "mailto:#{URI.encode_www_form_component(to).gsub('%40', ?@)}"
    extras = []
    extras << "cc=#{cc.map { |e| URI.encode_www_form_component(e).gsub('%40', ?@) }.join(',')}" if cc.present?
    extras << "from=#{URI.encode_www_form_component(from).gsub('%40', ?@)}" if from
    unless extras.empty?
      base << "?#{extras.join(?&)}"
    end
    "https://app.frontapp.com/compose?mailto=#{URI.encode_www_form_component(base)}"
  end
end

app/views/admin/sponsorships/_form.html.haml
- conference = sponsorship.conference
= form_with(model: sponsorship, url: conference_sponsorship_path(conference, sponsorship), class: 'sponsorships_form', local: true) do |form|

  - if sponsorship.errors.any?
    - I18n.with_options(scope: %i(errors template)) do |lo|
      .alert.alert-danger
        %p= lo.t :header, count: sponsorship.errors.count, model: sponsorship.class.name
        %ul
          - sponsorship.errors.full_messages.each do |message|
            %li= message

  %section.py-2
    .form-group
      %h3 Contact

    = form.fields_for :contact do |contact_form|
      .form-group
        = contact_form.label :email
        = contact_form.email_field :email, class: 'form-control', required: true

      .form-group
        = contact_form.label :email_cc
        = contact_form.text_field :email_cc, class: 'form-control'

      .form-group
        = contact_form.label :address
        = contact_form.text_field :address, class: 'form-control', required: true

      .form-group
        = contact_form.label :organization
        = contact_form.text_field :organization, class: 'form-control', required: true

      .form-group
        = contact_form.label :unit
        = contact_form.text_field :unit, class: 'form-control'

      .form-group
        = contact_form.label :name
        = contact_form.text_field :name, class: 'form-control', required: true

  %section.py-2.sponsorships_form_billing_contact
    .form-group
      %h3 Billing

    = form.fields_for :alternate_billing_contact do |contact_form|
      .form-group
        .form-check
          = contact_form.check_box :_keep, class: 'form-check-input'
          = contact_form.label :_keep, "Specify an alternate billing contact", class: 'form-check-label'

      %fieldset
        .form-group
          = contact_form.label :email
          = contact_form.email_field :email, class: 'form-control', required: true

        .form-group
          = contact_form.label :address
          = contact_form.text_field :address, class: 'form-control', required: true

        .form-group
          = contact_form.label :organization
          = contact_form.text_field :organization, class: 'form-control', required: true

        .form-group
          = contact_form.label :unit
          = contact_form.text_field :unit, class: 'form-control'

        .form-group
          = contact_form.label :name
          = contact_form.text_field :name, class: 'form-control', required: true

    = form.fields_for :billing_request do |request_form|
      .form-group
        = request_form.label :body
        = request_form.text_area :body, class: 'form-control'

  %section.py-2
    .form-group
      %h3 Plan

      - conference.plans.each do |plan|
        .form-check
          %label.form-check-label
            = form.radio_button :plan_id, plan.id, checked: plan.id == @sponsorship.plan_id, class: 'form-check-input', data: {booth: plan.booth_eligible? ? '1' : '0', words_limit_help: t('.plan_explanation.words_limit', count: plan.words_limit)}
            = plan.name
            %small<
              #{plan.price_text}
              , #{plan.number_of_guests}
              - if plan.booth_eligible?
                , #{plan.booth_size} booth
              - if plan.talkable?
                , Talk

      .form-check
        %label.form-check-label
          = form.radio_button :plan_id, '', checked: @sponsorship.plan_id == nil && (@sponsorship.persisted? || @sponsorship.errors.any?), class: 'form-check-input', data: {other: '1'}
          Other

    = form.fields_for :customization_request do |request_form|
      .form-group
        = request_form.label :body
        = request_form.text_area :body, class: 'form-control'

    .form-group
      %h5 Customization
    .form-group
      .form-check
        = form.check_box :customization, class: 'form-check-input'
        = form.label :customization, class: 'form-check-label'

    .form-group
      = form.label :customization_name
      = form.text_field :customization_name, class: 'form-control'

  %section.py-2
    .form-group
      %h3 Booth

    .form-group.sponsorships_form_booth_request
      .form-check
        = form.check_box :booth_requested, class: 'form-check-input'
        = form.label :booth_requested, class: 'form-check-label'
      %small.d-none.sponsorships_form_booth_request_uneligible.form-text.text-small.text-info Selected plan is uneligible for booth

    .form-group
      .form-check
        = form.check_box :booth_assigned, class: 'form-check-input'
        = form.label :booth_assigned, class: 'form-check-label'

  %section.py-2
    .form-group
      %h3 Fallback Option

    - form_desc = conference.form_description_for_locale
    - if form_desc&.fallback_options&.any?
      .form-group
        = form.label :fallback_option
        = form.select :fallback_option, options_for_select(form_desc.fallback_options.map {|opt| [opt.name, opt.value] }, sponsorship.fallback_option), {include_blank: '(none)'}, {class: 'form-control', required: false}

  %section.py-2
    .form-group
      %h3 Information

    .form-group
      = form.label :name
      = form.text_field :name, class: 'form-control', required: true

    .form-group
      = form.label :url
      = form.text_field :url, class: 'form-control', required: true

    .form-group
      = form.label :profile
      = form.text_area :profile, class: 'form-control', required: true
      %small.sponsorships_form_profile_help.form-text

  %section.py-2
    .form-group
      %h3 Logo

  %section.py-2
    .form-group
      %h3 Note from Sponsor

    = form.fields_for :note do |request_form|
      .form-group
        = request_form.label :body
        = request_form.text_area :body, class: 'form-control'

  %section.py-2
    .form-group
      %h3 Tickets

    .form-group
      = form.label :number_of_additional_attendees
      = form.number_field :number_of_additional_attendees, class: 'form-control'

  %section.py-2
    .form-group
      %h3 Administrative Flags

    .form-group
      .form-check
        = form.check_box :accepted, class: 'form-check-input'
        = form.label :accepted, class: 'form-check-label'

      .form-check
        = form.check_box :suspended, class: 'form-check-input'
        = form.label :suspended, class: 'form-check-label'
        %small.form-text Use this to suspend a presence in web sites etc, due to any problem on sponsor's introduction text.

  %section.py-2
    .form-group
      = form.submit "Save", class: 'btn btn-primary'

app/views/admin/sponsorships/edit.html.haml
- content_for(:title) { t('.title') }

%nav{aria: {label: 'breadcrumb'}}
  %ol.breadcrumb
    %li.breadcrumb-item= link_to @conference.name, conference_path(@conference)
    %li.breadcrumb-item Sponsorships
    %li.breadcrumb-item= link_to @sponsorship.name, [@conference, @sponsorship]
    %li.breadcrumb-item.active{aria: {current: 'page'}} Edit

= render 'form', sponsorship: @sponsorship

app/views/admin/sponsorships/show.html.haml
- content_for(:title) { t('.title', sponsorship: @sponsorship.name) }

%nav{aria: {label: 'breadcrumb'}}
  %ol.breadcrumb
    %li.breadcrumb-item= link_to @conference.name, conference_path(@conference)
    %li.breadcrumb-item Sponsorships
    %li.breadcrumb-item.active{aria: {current: 'page'}}= @sponsorship.name

.d-md-flex.justify-content-between
  %h3 #{@sponsorship.name}
  %div
    = link_to "Edit", edit_conference_sponsorship_path(@conference, @sponsorship), class: 'btn btn-primary'
    = link_to "History", conference_sponsorship_editing_histories_path(@conference, @sponsorship), class: 'btn btn-secondary'
    = link_to "Compose Email", front_mail_to_link(@sponsorship.contact.email, from: @conference.contact_email_address, cc: @sponsorship.contact.email_ccs), class: 'btn btn-info', target: '_blank'

.row
  .col-md-8
    .row
      .col-md-6
        .card
          %h5.card-header
            Basic Information
          .card-body
            %p.card-text
              - if @sponsorship.suspended?
                %span.badge.badge-warning Presence Suspended
              - if @sponsorship.withdrawn?
                %span.badge.badge-danger Withdrawn
              - if @sponsorship.accepted?
                %span.badge.badge-info Accepted
              - else
                %span.badge.badge-dark Not accepted
            %dl
              .row
                %dt.col-sm-4 Locale
                %dd.col-sm-8= @sponsorship.locale
              .row
                %dt.col-sm-4 Assets
                %dd.col-sm-8
                  &#x1F4C1;
                  = link_to 'Download', download_asset_conference_sponsorship_path(@conference, @sponsorship), class: 'card-link'
              .row
                %dt.col-sm-4 Booth
                %dd.col-sm-8
                  - case
                  - when @sponsorship.booth_assigned && !@sponsorship.booth_requested
                    &#x1F381; Assigned but Not requested (!?)
                  - when !@sponsorship.plan&.booth_eligible? && (@sponsorship.booth_assigned)
                    &#x1F49D; Not Eligible but Assigned (!?)
                  - when !@sponsorship.plan&.booth_eligible? && (@sponsorship.booth_requested)
                    &#x2753; Not Eligible but Requested (!?)
                  - when @sponsorship.booth_assigned
                    &#x2705; Assigned
                  - when @sponsorship.booth_requested
                    &#x1F5F3;&#xFE0F; Requested
                  - when @sponsorship.plan&.booth_eligible?
                    Eligible
                  - else
                    N/A

            %h5.card-title Plan

            - if @sponsorship.plan
              %p.card-text= @sponsorship.plan.name
            - else @sponsorship.plan
              %p.card-text
                %span.badge.badge-danger UNDETERMINED

            - if @sponsorship.fallback_option.present?
              %p.card-text.small
                Fallback:
                %code= @sponsorship.fallback_option

            - case
            - when @sponsorship.customized?
              %p.card-text Shown as: #{@sponsorship.customization_name}
            - when @sponsorship.customization_planned?
              %p.card-text
                #{@sponsorship.customization_name}
                %span.badge.badge-warning Custom Plan: Tentative

        .card.mt-2
          %h5.card-header
            Organization
          .card-body
            %p.card-text
              = link_to @sponsorship.organization.name, organization_path(@sponsorship.organization)

      .col-md-6
        .card
          %h5.card-header
            Invitations
          .card-body
            .row
              %dt.col-sm-4 Included
              %dd.col-sm-4= @sponsorship.plan&.number_of_guests || 0
            .row
              %dt.col-sm-4 Additional
              %dd.col-sm-4= @sponsorship.number_of_additional_attendees || 0
            .row
              %dt.col-sm-4 Total
              %dd.col-sm-4= @sponsorship.total_number_of_attendees
            - if @conference.tito_slug.present?
              .row
                .col-sm-12
                  %strong Tito Registration:
                  - if @sponsorship.tito_attendee_discount_code
                    = link_to "Attendee", @sponsorship.tito_attendee_discount_code.url
                  - if @sponsorship.tito_booth_staff_discount_code
                    = link_to "Exhibitor", @sponsorship.tito_booth_staff_discount_code.url
                  - if @sponsorship.tito_booth_paid_discount_code
                    = link_to "Exhibitor (Paid)", @sponsorship.tito_booth_paid_discount_code.url
              .row
                .col-sm-12
                  %strong Tito Admin:
                  - if @sponsorship.tito_attendee_discount_code
                    = link_to "Attendee", @sponsorship.tito_attendee_discount_code.dashboard_orders_url
                  - if @sponsorship.tito_booth_staff_discount_code
                    = link_to "Exhibitor", @sponsorship.tito_booth_staff_discount_code.dashboard_orders_url
                  - if @sponsorship.tito_booth_paid_discount_code
                    = link_to "Exhibitor (Paid)", @sponsorship.tito_booth_paid_discount_code.dashboard_orders_url
        .card
          %h5.card-header
            Requests
          .card-body
            - if @sponsorship.customization_request&.body&.present?
              %h5.card-title Customization
              %p.card-text
                - @sponsorship.customization_request.body.each_line do |l|
                  = l
                  %br

            - if @sponsorship.billing_request&.body&.present?
              %h5.card-title Billing
              %p.card-text
                - @sponsorship.billing_request.body.each_line do |l|
                  = l
                  %br

            - if @sponsorship.note&.body&.present?
              %h5.card-title Others
              %p.card-text
                - @sponsorship.note.body.each_line do |l|
                  = l
                  %br

        - if @sponsorship.booth_assigned?
          .card.mt-2
            %h5.card-header
              Booth Details
            .card-body
              - if @sponsorship.exhibition
                %p.card-text
                  - @sponsorship.exhibition.description.each_line do |l|
                    = l
                    %br
              - else
                %p.card-text
                  %span.badge.badge-warning Not submitted

        - events = @sponsorship.sponsor_events.by_starts_at
        - if events.any?
          .card.mt-2
            %h5.card-header
              Events
            %ul.list-group.list-group-flush
              - events.each do |event|
                %li.list-group-item.d-flex.justify-content-between.align-items-center
                  = link_to event.title, conference_sponsor_event_path(@conference, event)
                  - case event.status
                  - when 'pending'
                    %span.badge.badge-warning pending
                  - when 'accepted'
                    %span.badge.badge-success accepted
                  - when 'rejected'
                    %span.badge.badge-danger rejected
                  - when 'withdrawn'
                    %span.badge.badge-secondary withdrawn

    .row
      .col-md-12
        .card.mt-2
          %h5.card-header
            Introduction
          .card-body
            %h5.card-title= @sponsorship.name
            %p.card-text= @sponsorship.profile
            .d-flex.justify-content-between
              %a.card-link{href: @sponsorship.url, target: '_blank'}= @sponsorship.url
              %small
                #{@sponsorship.word_count} words
                - if @sponsorship.plan&.words_limit
                  #{@sponsorship.plan.words_limit} or #{@sponsorship.plan.words_limit_hard&.to_i}
  .col-md-4
    .card
      .card-header.d-flex.justify-content-between
        %h5.my-auto Notes
        = link_to "Show All", conference_sponsorship_staff_notes_path(@conference, @sponsorship), class: 'btn btn-default small'
      %ul.list-group.list-group-flush
        %li.list-group-item
          = render 'admin/sponsorship_staff_notes/form', staff_note: @new_staff_note
        - [*@pinned_staff_notes, *@staff_notes].each do |note|
          %li.list-group-item
            = render 'admin/sponsorship_staff_notes/item', staff_note: note


.row.mt-2
  .col-md-4
    .card
      %h5.card-header Contact
      .card-body
        .row
        %p.card-text
          #{@sponsorship.contact.name}
          = link_to @sponsorship.contact.email, front_mail_to_link(@sponsorship.contact.email, from: @conference.contact_email_address, cc: @sponsorship.contact.email_ccs), target: '_blank'
        %p.card-text
          - if @sponsorship.contact.unit
            = @sponsorship.contact.unit
            %br
          = @sponsorship.contact.organization
        %p.card-text
          = @sponsorship.contact.address

  .col-md-4
    .card
      %h5.card-header
        Billing
        - if @sponsorship.alternate_billing_contact
          %span.badge.badge-danger Alternate billing contact specified
      .card-body
        %p.card-text
          #{@sponsorship.billing_contact.name}
          = link_to @sponsorship.billing_contact.email, front_mail_to_link(@sponsorship.billing_contact.email, from: @conference.contact_email_address, cc: @sponsorship.billing_contact.email_ccs), target: '_blank'
        %p.card-text
          - if @sponsorship.billing_contact.unit
            = @sponsorship.billing_contact.unit
            %br
          = @sponsorship.billing_contact.organization
        %p.card-text
          = @sponsorship.billing_contact.address


.row.mt-4
  .col-md-8
    %section.card.border-danger
      .card-header.bg-danger.text-white Danger Zone
      .card-body
        %p.card-text
          - if @sponsorship.withdrawn?
          - else
            = link_to "Withdraw", conference_sponsorship_path(@conference, @sponsorship), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'
          - if Rails.configuration.x.dev.sponsor_impersonation
            = link_to "Impersonate", conference_sponsorship_impersonation_path(@conference, @sponsorship), method: :post, class: 'btn btn-warning'